services:
  postgres:
    image: postgres:17
    container_name: postgres_db_event
    restart: always
    environment:
      POSTGRES_USER: eventUser
      POSTGRES_PASSWORD: eventbookingpassword
      POSTGRES_DB: EventBookingDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # Port สำหรับให้ Spring Boot ส่งข้อความเข้ามา
      - "15672:15672" # Port สำหรับหน้าเว็บ Dashboard
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      -
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # (Option) ป้องกันคิวหายเวลาปิด Container
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data: