services:
  postgres:
    image: postgres:17
    container_name: postgres_db_event
    restart: always
    environment:
      POSTGRES_USER: eventUser
      POSTGRES_PASSWORD: eventbookingpassword
      POSTGRES_DB: EventBookingDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: