spring.application.name=Event Ticket Booking System

spring.datasource.url=jdbc:postgresql://localhost:5432/EventBookingDB
spring.datasource.username=eventUser
spring.datasource.password=eventbookingpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=qH38vXUsnz84YkG5pjYHywW1d/5m0hQ5eGVdsaFFD456
jwt.expiration=3600000

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest